import AppKit
import Observation

/// The last text items copied, for the taskbar's clipboard popup (Win+V).
/// Kept in memory only — never written to disk — and anything a password
/// manager marks as concealed or transient is skipped.
@MainActor
@Observable
final class ClipboardHistory {
    static let shared = ClipboardHistory()

    private(set) var items: [String] = []

    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChangeCount = NSPasteboard.general.changeCount

    private static let limit = 25
    private static let maxLength = 5000
    private static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    func startPolling() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
    }

    func stopPolling() {
        timer?.invalidate()
        timer = nil
        items = []
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let types = pasteboard.types ?? []
        guard !Self.ignoredTypes.contains(where: types.contains),
              let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.count <= Self.maxLength else { return }
        items.removeAll { $0 == text }
        items.insert(text, at: 0)
        if items.count > Self.limit { items.removeLast(items.count - Self.limit) }
    }

    func clear() { items = [] }

    /// Puts `text` back on the clipboard and pastes it into the app that's
    /// in front (this app's panels never take focus, so it still is).
    func paste(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        items.removeAll { $0 == text }
        items.insert(text, at: 0)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) {
            let source = CGEventSource(stateID: .hidSystemState)
            let vKey: CGKeyCode = 0x09
            for down in [true, false] {
                let event = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: down)
                event?.flags = .maskCommand
                event?.post(tap: .cghidEventTap)
            }
        }
    }
}
